kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: imagestream-job-role
  namespace: redhat-ods-applications
rules:
  - verbs:
      - get
      - list
      - delete
      - create
      - watch
      - update
      - patch
    apiGroups:
      - ""
    resources:
      - serviceaccounts
  - verbs:
      - get
      - create
      - list
      - delete
      - update
      - watch
      - patch
    apiGroups:
      - "batch"
    resources:
      - jobs
  - verbs:
      - get
      - create
      - list
    apiGroups:
      - "image.openshift.io"
    resources:
      - imagestreams
