kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: imagestream-job-rolebinding
  namespace: redhat-ods-applications
subjects:
  - kind: ServiceAccount
    name: imagestream-job
    namespace: redhat-ods-applications
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: imagestream-job-role
